import type { TickerInfo } from '../types';

export const ALL_TICKERS: TickerInfo[] = [
  // --- NSE Large Cap Equities ---
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Energy & Petrochemicals' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'INFY.NS', name: 'Infosys Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Telecommunications' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever Limited', exchange: 'NSE', type: 'EQUITY', sector: 'FMCG' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Infrastructure & Construction' },
  { symbol: 'ITC.NS', name: 'ITC Limited', exchange: 'NSE', type: 'EQUITY', sector: 'FMCG' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Consumer Goods' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Automobiles' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical Industries Ltd', exchange: 'NSE', type: 'EQUITY', sector: 'Pharmaceuticals' },
  { symbol: 'TITAN.NS', name: 'Titan Company Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Consumer Goods' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'WIPRO.NS', name: 'Wipro Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Cement & Building Materials' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Automobiles' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Metals & Mining' },
  { symbol: 'ONGC.NS', name: 'Oil and Natural Gas Corporation Ltd', exchange: 'NSE', type: 'EQUITY', sector: 'Energy & Petrochemicals' },
  { symbol: 'NTPC.NS', name: 'NTPC Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Power & Utilities' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation of India Ltd', exchange: 'NSE', type: 'EQUITY', sector: 'Power & Utilities' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Conglomerate' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports and SEZ Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Infrastructure & Construction' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Metals & Mining' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Automobiles' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India Limited', exchange: 'NSE', type: 'EQUITY', sector: 'FMCG' },
  { symbol: 'DRREDDY.NS', name: 'Dr. Reddy\'s Laboratories Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Pharmaceuticals' },
  { symbol: 'CIPLA.NS', name: 'Cipla Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Pharmaceuticals' },
  { symbol: 'DIVISLAB.NS', name: 'Divi\'s Laboratories Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Pharmaceuticals' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals Enterprise Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Healthcare' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Diversified' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum Corporation Ltd', exchange: 'NSE', type: 'EQUITY', sector: 'Energy & Petrochemicals' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Automobiles' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Automobiles' },
  { symbol: 'COALINDIA.NS', name: 'Coal India Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Metals & Mining' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products Limited', exchange: 'NSE', type: 'EQUITY', sector: 'FMCG' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries Limited', exchange: 'NSE', type: 'EQUITY', sector: 'FMCG' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Cement & Building Materials' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Chemicals' },
  { symbol: 'DMART.NS', name: 'Avenue Supermarts Limited (DMart)', exchange: 'NSE', type: 'EQUITY', sector: 'Retail' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance Company Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Insurance' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance Company Ltd', exchange: 'NSE', type: 'EQUITY', sector: 'Insurance' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life Insurance', exchange: 'NSE', type: 'EQUITY', sector: 'Insurance' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Automobiles' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Metals & Mining' },
  { symbol: 'VEDL.NS', name: 'Vedanta Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Metals & Mining' },
  { symbol: 'ZOMATO.NS', name: 'Zomato Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Consumer Internet' },
  { symbol: 'PAYTM.NS', name: 'One97 Communications Limited (Paytm)', exchange: 'NSE', type: 'EQUITY', sector: 'FinTech' },
  { symbol: 'NYKAA.NS', name: 'FSN E-Commerce Ventures Limited (Nykaa)', exchange: 'NSE', type: 'EQUITY', sector: 'E-Commerce' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance Corporation', exchange: 'NSE', type: 'EQUITY', sector: 'Government Finance' },
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Defence' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Defence' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Infrastructure & Construction' },
  { symbol: 'PFC.NS', name: 'Power Finance Corporation Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Government Finance' },
  { symbol: 'RECLTD.NS', name: 'REC Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Government Finance' },
  { symbol: 'BSE.NS', name: 'BSE Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Capital Markets' },
  { symbol: 'CDSL.NS', name: 'Central Depository Services (India) Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Capital Markets' },
  { symbol: 'ANGELONE.NS', name: 'Angel One Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Capital Markets' },
  { symbol: 'CAMS.NS', name: 'Computer Age Management Services Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Capital Markets' },
  { symbol: 'KFINTECH.NS', name: 'KFin Technologies Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Capital Markets' },
  { symbol: 'MCX.NS', name: 'Multi Commodity Exchange of India Limited', exchange: 'NSE', type: 'EQUITY', sector: 'Capital Markets' },

  // --- BSE Equities ---
  { symbol: 'RELIANCE.BO', name: 'Reliance Industries Limited', exchange: 'BSE', type: 'EQUITY', sector: 'Energy & Petrochemicals' },
  { symbol: 'TCS.BO', name: 'Tata Consultancy Services Limited', exchange: 'BSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'HDFCBANK.BO', name: 'HDFC Bank Limited', exchange: 'BSE', type: 'EQUITY', sector: 'Banking & Finance' },
  { symbol: 'INFY.BO', name: 'Infosys Limited', exchange: 'BSE', type: 'EQUITY', sector: 'Information Technology' },
  { symbol: 'TATAMOTORS.BO', name: 'Tata Motors Limited', exchange: 'BSE', type: 'EQUITY', sector: 'Automobiles' },

  // --- MCX Commodities (Yahoo Finance futures symbols) ---
  { symbol: 'GC=F',  name: 'Gold',         exchange: 'MCX', type: 'COMMODITY', sector: 'Precious Metals' },
  { symbol: 'SI=F',  name: 'Silver',        exchange: 'MCX', type: 'COMMODITY', sector: 'Precious Metals' },
  { symbol: 'CL=F',  name: 'Crude Oil',     exchange: 'MCX', type: 'COMMODITY', sector: 'Energy' },
  { symbol: 'NG=F',  name: 'Natural Gas',   exchange: 'MCX', type: 'COMMODITY', sector: 'Energy' },
  { symbol: 'HG=F',  name: 'Copper',        exchange: 'MCX', type: 'COMMODITY', sector: 'Base Metals' },
  { symbol: 'ALI=F', name: 'Aluminium',     exchange: 'MCX', type: 'COMMODITY', sector: 'Base Metals' },
  { symbol: 'ZW=F',  name: 'Wheat',         exchange: 'MCX', type: 'COMMODITY', sector: 'Agricultural' },
  { symbol: 'ZC=F',  name: 'Corn',          exchange: 'MCX', type: 'COMMODITY', sector: 'Agricultural' },
  { symbol: 'PL=F',  name: 'Platinum',      exchange: 'MCX', type: 'COMMODITY', sector: 'Precious Metals' },
  { symbol: 'PA=F',  name: 'Palladium',     exchange: 'MCX', type: 'COMMODITY', sector: 'Precious Metals' },

  // --- Indices ---
  { symbol: '^NSEI', name: 'NIFTY 50', exchange: 'INDEX', type: 'INDEX' },
  { symbol: '^NSEBANK', name: 'Bank NIFTY', exchange: 'INDEX', type: 'INDEX' },
  { symbol: '^BSESN', name: 'BSE SENSEX', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYMIDCAP100.NS', name: 'NIFTY Midcap 100', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYSMALLCAP100.NS', name: 'NIFTY Smallcap 100', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYIT.NS', name: 'NIFTY IT Index', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYPHARMA.NS', name: 'NIFTY Pharma Index', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYAUTO.NS', name: 'NIFTY Auto Index', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYFMCG.NS', name: 'NIFTY FMCG Index', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYMETAL.NS', name: 'NIFTY Metal Index', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYREALTY.NS', name: 'NIFTY Realty Index', exchange: 'INDEX', type: 'INDEX' },
  { symbol: 'NIFTYINFRA.NS', name: 'NIFTY Infrastructure Index', exchange: 'INDEX', type: 'INDEX' },

  // --- ETFs ---
  { symbol: 'GOLDBEES.NS', name: 'Nippon India ETF Gold BeES', exchange: 'NSE', type: 'ETF', sector: 'Precious Metals' },
  { symbol: 'LIQUIDBEES.NS', name: 'Nippon India ETF Liquid BeES', exchange: 'NSE', type: 'ETF', sector: 'Liquid' },
  { symbol: 'NIFTYBEES.NS', name: 'Nippon India ETF Nifty BeES', exchange: 'NSE', type: 'ETF', sector: 'Index' },
  { symbol: 'BANKBEES.NS', name: 'Nippon India ETF Bank BeES', exchange: 'NSE', type: 'ETF', sector: 'Banking' },
  { symbol: 'ICICINIFTY.NS', name: 'ICICI Prudential Nifty 50 ETF', exchange: 'NSE', type: 'ETF', sector: 'Index' },
];

/** Tickers shown in the scrolling market pulse ticker tape */
export const TAPE_TICKERS: string[] = [
  '^NSEI',
  '^BSESN',
  '^NSEBANK',
  'GC=F',
  'CL=F',
  'SI=F',
  'HG=F',
  'RELIANCE.NS',
  'TCS.NS',
  'HDFCBANK.NS',
];

/** Canonical list of display sectors for the heatmap */
export const SECTOR_LIST: string[] = [
  'Banking',
  'IT',
  'Energy',
  'Metal',
  'Pharma',
  'Automobile',
  'FMCG',
  'Infrastructure',
  'Consumer',
  'NBFC',
];

